### ISSUE TITLE
gp base value

### ISSUE THREAD

**Issue by nistra123** [Road-block/BastionLoot#4]
hey, not really an issue but idk how to contact you otherwise - is there a way to set base value of GP to 1 and not 100? i changed systems and dont want to set up everyone manually everytime someone below 100gp receives an item

**Comment by Road-block** [comment]
You could edit your local copy, there's no setting for it currently.  
Editing [this line](https://github.com/Road-block/BastionLoot/blob/db17ddb2d5871d69d0194861ecffb3af2c1c8743/core.lua#L18) in your local copy to 1 would do what you want if you are the only person doing masterlooting.  

I could make it a setting like decay and offspec price but what's the problem with a 100 GP base value if I may ask?

**Comment by nistra123** [comment]
hey, thank you for the fast answer. there is no problem with 100 base gp in general, i just swapped from another addon that caused heavy lag on my pc and that addon had 1 gp base and i wanted to make it like before for all the raiders
